title: Neptune's Needle
email: ahoy@frigat.es 
description: Interactive Database of Maritime History
url: "http://neptunesneedle.com/"
baseurl: ""
permalink: /:categories/:title/
category-list: [people, ships, events, locations, documents, mapchart]
